# **Notebook 01**: Inventário e Concatenação
---

**Projeto:** Bellabeat Data Analysis (Kaggle FitBit Dataset)  
**Autor:** Alessandro Moreira Cecilio  
**Data:** Outubro / 2026  

### Objetivo
Realizar o inventário das tabelas brutas disponíveis, selecionar os conjuntos de dados estratégicos para a análise de negócios e concatenar os dados dos dois meses (Append).

### Etapas

Neste notebook serão realizadas as seguintes etapas:

*1. Importação das bibliotecas necessárias;*<br>
*2. Inspeção Inicial: Identificação e compreensão das variáveis e tabelas disponíveis;*<br>
*3. Seleção das tabelas a serem usadas no projeto;*<br>
*4. Concatenação dos datasets selecionados;*<br>
*5. Sanity Check pós-concatenação;*<br>
*6. Salvamento do dataset consolidado para utilização nas etapas seguintes;*<br>


> **Observação:** Esta etapa tem como foco compreender os dados e identificar possíveis problemas. Questões relacionadas à qualidade dos dados, como valores ausentes, duplicidades, inconsistências e erros de tipagem, serão investigadas e tratadas no próximo notebook.

---

---

## 1. Importação das Bibliotecas

In [1]:
# Configuração do Jupyter (Autoreload)
%load_ext autoreload
%autoreload 2

# Imports 
import os
import sys
from pathlib import Path
import pandas as pd

# Adiciona a raiz do projeto ao sys.path para conseguir importar a pasta src
sys.path.append(os.path.abspath('..'))

from src.data_loader import inspect_samples, load_and_concatenate_csvs

RAW_DATA_PATH = "../data/raw"

---

## 2. Inspeção Inicial

In [2]:
# Carrega amostras de 3 linhas de todas as tabelas
samples = inspect_samples(RAW_DATA_PATH, n_rows=3)

print(f"Total de tabelas encontradas no dataset: {len(samples)}\n")

# Exibe as colunas e as primeiras linhas de cada tabela para tomada de decisão
for table_name, df_sample in samples.items():
    print(f"=== TABELA: {table_name} ===")
    print(f"Colunas ({len(df_sample.columns)}): {list(df_sample.columns)}")
    display(df_sample)
    print("\n" + "-" * 60 + "\n")

Total de tabelas encontradas no dataset: 18

=== TABELA: dailyActivity_merged ===
Colunas (15): ['Id', 'ActivityDate', 'TotalSteps', 'TotalDistance', 'TrackerDistance', 'LoggedActivitiesDistance', 'VeryActiveDistance', 'ModeratelyActiveDistance', 'LightActiveDistance', 'SedentaryActiveDistance', 'VeryActiveMinutes', 'FairlyActiveMinutes', 'LightlyActiveMinutes', 'SedentaryMinutes', 'Calories']

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,4/12/2016,13162,8.50,8.50,0,1.88,0.55,6.06,0,25,13,328,728,1985
1,1503960366,4/13/2016,10735,6.97,6.97,0,1.57,0.69,4.71,0,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.74,6.74,0,2.44,0.40,3.91,0,30,11,181,1218,1776

------------------------------------------------------------

=== TABELA: dailyCalories_merged ===
Colunas (3): ['Id', 'ActivityDay', 'Calories']

           Id ActivityDay  Calories
0  1503960366   4/12/2016      1985
1  1503960366   4/13/2016      1797
2  1503960366   4/14/2016      1776

------------------------------------------------------------

=== TABELA: dailyIntensities_merged ===
Colunas (10): ['Id', 'ActivityDay', 'SedentaryMinutes', 'LightlyActiveMinutes', 'FairlyActiveMinutes', 'VeryActiveMinutes', 'SedentaryActiveDistance', 'LightActiveDistance', 'ModeratelyActiveDistance', 'VeryActiveDistance']

,Id,ActivityDay,SedentaryMinutes,LightlyActiveMinutes,FairlyActiveMinutes,VeryActiveMinutes,SedentaryActiveDistance,LightActiveDistance,ModeratelyActiveDistance,VeryActiveDistance
0,1503960366,4/12/2016,728,328,13,25,0,6.06,0.55,1.88
1,1503960366,4/13/2016,776,217,19,21,0,4.71,0.69,1.57
2,1503960366,4/14/2016,1218,181,11,30,0,3.91,0.40,2.44

------------------------------------------------------------

=== TABELA: dailySteps_merged ===
Colunas (3): ['Id', 'ActivityDay', 'StepTotal']

           Id ActivityDay  StepTotal
0  1503960366   4/12/2016      13162
1  1503960366   4/13/2016      10735
2  1503960366   4/14/2016      10460

------------------------------------------------------------

=== TABELA: heartrate_seconds_merged ===
Colunas (3): ['Id', 'Time', 'Value']

           Id                  Time  Value
0  2022484408  4/12/2016 7:21:00 AM     97
1  2022484408  4/12/2016 7:21:05 AM    102
2  2022484408  4/12/2016 7:21:10 AM    105

------------------------------------------------------------

=== TABELA: hourlyCalories_merged ===
Colunas (3): ['Id', 'ActivityHour', 'Calories']

           Id           ActivityHour  Calories
0  1503960366  4/12/2016 12:00:00 AM        81
1  1503960366   4/12/2016 1:00:00 AM        61
2  1503960366   4/12/2016 2:00:00 AM        59

------------------------------------------------------------

=== TABELA: hourlyIntensities_merged ===
Colunas (4): ['Id', 'ActivityHour', 'TotalIntensity', 'AverageIntensity']

           Id           ActivityHour  TotalIntensity  AverageIntensity
0  1503960366  4/12/2016 12:00:00 AM              20          0.333333
1  1503960366   4/12/2016 1:00:00 AM               8          0.133333
2  1503960366   4/12/2016 2:00:00 AM               7          0.116667

------------------------------------------------------------

=== TABELA: hourlySteps_merged ===
Colunas (3): ['Id', 'ActivityHour', 'StepTotal']

           Id           ActivityHour  StepTotal
0  1503960366  4/12/2016 12:00:00 AM        373
1  1503960366   4/12/2016 1:00:00 AM        160
2  1503960366   4/12/2016 2:00:00 AM        151

------------------------------------------------------------

=== TABELA: minuteCaloriesNarrow_merged ===
Colunas (3): ['Id', 'ActivityMinute', 'Calories']

           Id         ActivityMinute  Calories
0  1503960366  4/12/2016 12:00:00 AM    0.7865
1  1503960366  4/12/2016 12:01:00 AM    0.7865
2  1503960366  4/12/2016 12:02:00 AM    0.7865

------------------------------------------------------------

=== TABELA: minuteCaloriesWide_merged ===
Colunas (62): ['Id', 'ActivityHour', 'Calories00', 'Calories01', 'Calories02', 'Calories03', 'Calories04', 'Calories05', 'Calories06', 'Calories07', 'Calories08', 'Calories09', 'Calories10', 'Calories11', 'Calories12', 'Calories13', 'Calories14', 'Calories15', 'Calories16', 'Calories17', 'Calories18', 'Calories19', 'Calories20', 'Calories21', 'Calories22', 'Calories23', 'Calories24', 'Calories25', 'Calories26', 'Calories27', 'Calories28', 'Calories29', 'Calories30', 'Calories31', 'Calories32', 'Calories33', 'Calories34', 'Calories35', 'Calories36', 'Calories37', 'Calories38', 'Calories39', 'Calories40', 'Calories41', 'Calories42', 'Calories43', 'Calories44', 'Calories45', 'Calories46', 'Calories47', 'Calories48', 'Calories49', 'Calories50', 'Calories51', 'Calories52', 'Calories53', 'Calories54', 'Calories55', 'Calories56', 'Calories57', 'Calories58', 'Calories59']

,Id,ActivityHour,Calories00,Calories01,Calories02,Calories03,Calories04,Calories05,Calories06,Calories07,...,Calories50,Calories51,Calories52,Calories53,Calories54,Calories55,Calories56,Calories57,Calories58,Calories59
0,1503960366,4/13/2016 12:00:00 AM,1.8876,2.2022,0.9438,0.9438,0.9438,2.0449,0.9438,2.2022,...,0.9438,2.0449,2.0449,0.9438,2.3595,1.8876,0.9438,0.9438,0.9438,0.9438
1,1503960366,4/13/2016 1:00:00 AM,0.7865,0.7865,0.7865,0.7865,0.9438,0.9438,0.9438,0.7865,...,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865
2,1503960366,4/13/2016 2:00:00 AM,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,...,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865

------------------------------------------------------------

=== TABELA: minuteIntensitiesNarrow_merged ===
Colunas (3): ['Id', 'ActivityMinute', 'Intensity']

           Id         ActivityMinute  Intensity
0  1503960366  4/12/2016 12:00:00 AM          0
1  1503960366  4/12/2016 12:01:00 AM          0
2  1503960366  4/12/2016 12:02:00 AM          0

------------------------------------------------------------

=== TABELA: minuteIntensitiesWide_merged ===
Colunas (62): ['Id', 'ActivityHour', 'Intensity00', 'Intensity01', 'Intensity02', 'Intensity03', 'Intensity04', 'Intensity05', 'Intensity06', 'Intensity07', 'Intensity08', 'Intensity09', 'Intensity10', 'Intensity11', 'Intensity12', 'Intensity13', 'Intensity14', 'Intensity15', 'Intensity16', 'Intensity17', 'Intensity18', 'Intensity19', 'Intensity20', 'Intensity21', 'Intensity22', 'Intensity23', 'Intensity24', 'Intensity25', 'Intensity26', 'Intensity27', 'Intensity28', 'Intensity29', 'Intensity30', 'Intensity31', 'Intensity32', 'Intensity33', 'Intensity34', 'Intensity35', 'Intensity36', 'Intensity37', 'Intensity38', 'Intensity39', 'Intensity40', 'Intensity41', 'Intensity42', 'Intensity43', 'Intensity44', 'Intensity45', 'Intensity46', 'Intensity47', 'Intensity48', 'Intensity49', 'Intensity50', 'Intensity51', 'Intensity52', 'Intensity53', 'Intensity54', 'Intensity55', 'Intensity56', 'Intensity57', 'Intensity58', 'Intensity59']

,Id,ActivityHour,Intensity00,Intensity01,Intensity02,Intensity03,Intensity04,Intensity05,Intensity06,Intensity07,...,Intensity50,Intensity51,Intensity52,Intensity53,Intensity54,Intensity55,Intensity56,Intensity57,Intensity58,Intensity59
0,1503960366,4/13/2016 12:00:00 AM,1,1,0,0,0,1,0,1,...,0,1,1,0,1,1,0,0,0,0
1,1503960366,4/13/2016 1:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1503960366,4/13/2016 2:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

------------------------------------------------------------

=== TABELA: minuteMETsNarrow_merged ===
Colunas (3): ['Id', 'ActivityMinute', 'METs']

           Id         ActivityMinute  METs
0  1503960366  4/12/2016 12:00:00 AM    10
1  1503960366  4/12/2016 12:01:00 AM    10
2  1503960366  4/12/2016 12:02:00 AM    10

------------------------------------------------------------

=== TABELA: minuteSleep_merged ===
Colunas (4): ['Id', 'date', 'value', 'logId']

           Id                  date  value        logId
0  1503960366  4/12/2016 2:47:30 AM      3  11380564589
1  1503960366  4/12/2016 2:48:30 AM      2  11380564589
2  1503960366  4/12/2016 2:49:30 AM      1  11380564589

------------------------------------------------------------

=== TABELA: minuteStepsNarrow_merged ===
Colunas (3): ['Id', 'ActivityMinute', 'Steps']

           Id         ActivityMinute  Steps
0  1503960366  4/12/2016 12:00:00 AM      0
1  1503960366  4/12/2016 12:01:00 AM      0
2  1503960366  4/12/2016 12:02:00 AM      0

------------------------------------------------------------

=== TABELA: minuteStepsWide_merged ===
Colunas (62): ['Id', 'ActivityHour', 'Steps00', 'Steps01', 'Steps02', 'Steps03', 'Steps04', 'Steps05', 'Steps06', 'Steps07', 'Steps08', 'Steps09', 'Steps10', 'Steps11', 'Steps12', 'Steps13', 'Steps14', 'Steps15', 'Steps16', 'Steps17', 'Steps18', 'Steps19', 'Steps20', 'Steps21', 'Steps22', 'Steps23', 'Steps24', 'Steps25', 'Steps26', 'Steps27', 'Steps28', 'Steps29', 'Steps30', 'Steps31', 'Steps32', 'Steps33', 'Steps34', 'Steps35', 'Steps36', 'Steps37', 'Steps38', 'Steps39', 'Steps40', 'Steps41', 'Steps42', 'Steps43', 'Steps44', 'Steps45', 'Steps46', 'Steps47', 'Steps48', 'Steps49', 'Steps50', 'Steps51', 'Steps52', 'Steps53', 'Steps54', 'Steps55', 'Steps56', 'Steps57', 'Steps58', 'Steps59']

,Id,ActivityHour,Steps00,Steps01,Steps02,Steps03,Steps04,Steps05,Steps06,Steps07,...,Steps50,Steps51,Steps52,Steps53,Steps54,Steps55,Steps56,Steps57,Steps58,Steps59
0,1503960366,4/13/2016 12:00:00 AM,4,16,0,0,0,9,0,17,...,0,9,8,0,20,1,0,0,0,0
1,1503960366,4/13/2016 1:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1503960366,4/13/2016 2:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

------------------------------------------------------------

=== TABELA: sleepDay_merged ===
Colunas (5): ['Id', 'SleepDay', 'TotalSleepRecords', 'TotalMinutesAsleep', 'TotalTimeInBed']

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,4/12/2016 12:00:00 AM,1,327,346
1,1503960366,4/13/2016 12:00:00 AM,2,384,407
2,1503960366,4/15/2016 12:00:00 AM,1,412,442

------------------------------------------------------------

=== TABELA: weightLogInfo_merged ===
Colunas (8): ['Id', 'Date', 'WeightKg', 'WeightPounds', 'Fat', 'BMI', 'IsManualReport', 'LogId']

,Id,Date,WeightKg,WeightPounds,Fat,BMI,IsManualReport,LogId
0,1503960366,5/2/2016 11:59:59 PM,52.599998,115.963147,22.0,22.650000,True,1462233599000
1,1503960366,5/3/2016 11:59:59 PM,52.599998,115.963147,NaN,22.650000,True,1462319999000
2,1927972279,4/13/2016 1:08:52 AM,133.500000,294.317120,NaN,47.540001,False,1460509732000

------------------------------------------------------------

---

## 3. Seleção de Tabelas

In [3]:
# Selecao baseada na exploracao
tabelas_selecionadas = [
    "dailyActivity_merged",
    "sleepDay_merged",
    "weightLogInfo_merged",
    "hourlySteps_merged"
]

---

## 4. Concatenação dos Datasets Selecionados

In [4]:
# Carregamento e Concatenacao (usando o loop da funcao do src
dfs = {} # Dicionario para armazenar nossos DataFrames

for nome_tabela in tabelas_selecionadas:
    print(f"Carregando e concatenando: {nome_tabela}...")
    dfs[nome_tabela] = load_and_concatenate_csvs(RAW_DATA_PATH, nome_tabela)

print("\nCarga finalizada!")

Carregando e concatenando: dailyActivity_merged...
Carregando e concatenando: sleepDay_merged...
Carregando e concatenando: weightLogInfo_merged...
Carregando e concatenando: hourlySteps_merged...

Carga finalizada!

--- 

## 5. Sanity Check Pós-concatenação

In [5]:
# Relatório pós-concatenação
for table_name, df in dfs.items():
    print(f"=== {table_name.upper()} ===")
    print(f"Volume: {df.shape[0]} linhas e {df.shape[1]} colunas")
    
    # Exibe os tipos de dados que o Pandas identificou automaticamente
    print("Tipos de Dados:")
    display(df.dtypes.to_frame(name="Tipo").T)
    
    # Exibe as 3 primeiras linhas para checar se a estrutura faz sentido
    display(df.head(3))
    print("\n" + "="*80 + "\n")

=== DAILYACTIVITY_MERGED ===
Volume: 1397 linhas e 16 colunas
Tipos de Dados:

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,source_folder
Tipo,int64,str,int64,float64,float64,float64,float64,float64,float64,float64,int64,int64,int64,int64,int64,str

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,source_folder
0,1503960366,4/12/2016,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985,Fitabase Data 4.12.16-5.12.16
1,1503960366,4/13/2016,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797,Fitabase Data 4.12.16-5.12.16
2,1503960366,4/14/2016,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776,Fitabase Data 4.12.16-5.12.16

================================================================================

=== SLEEPDAY_MERGED ===
Volume: 413 linhas e 6 colunas
Tipos de Dados:

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed,source_folder
Tipo,int64,str,int64,int64,int64,str

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed,source_folder
0,1503960366,4/12/2016 12:00:00 AM,1,327,346,Fitabase Data 4.12.16-5.12.16
1,1503960366,4/13/2016 12:00:00 AM,2,384,407,Fitabase Data 4.12.16-5.12.16
2,1503960366,4/15/2016 12:00:00 AM,1,412,442,Fitabase Data 4.12.16-5.12.16

================================================================================

=== WEIGHTLOGINFO_MERGED ===
Volume: 100 linhas e 9 colunas
Tipos de Dados:

,Id,Date,WeightKg,WeightPounds,Fat,BMI,IsManualReport,LogId,source_folder
Tipo,int64,str,float64,float64,float64,float64,bool,int64,str

,Id,Date,WeightKg,WeightPounds,Fat,BMI,IsManualReport,LogId,source_folder
0,1503960366,5/2/2016 11:59:59 PM,52.599998,115.963147,22.0,22.650000,True,1462233599000,Fitabase Data 4.12.16-5.12.16
1,1503960366,5/3/2016 11:59:59 PM,52.599998,115.963147,NaN,22.650000,True,1462319999000,Fitabase Data 4.12.16-5.12.16
2,1927972279,4/13/2016 1:08:52 AM,133.500000,294.317120,NaN,47.540001,False,1460509732000,Fitabase Data 4.12.16-5.12.16

================================================================================

=== HOURLYSTEPS_MERGED ===
Volume: 46183 linhas e 4 colunas
Tipos de Dados:

         Id ActivityHour StepTotal source_folder
Tipo  int64          str     int64           str

           Id           ActivityHour  StepTotal                  source_folder
0  1503960366  4/12/2016 12:00:00 AM        373  Fitabase Data 4.12.16-5.12.16
1  1503960366   4/12/2016 1:00:00 AM        160  Fitabase Data 4.12.16-5.12.16
2  1503960366   4/12/2016 2:00:00 AM        151  Fitabase Data 4.12.16-5.12.16

================================================================================

---

## 6. Salvamento dos Dados Consolidados

In [6]:
# Garante que a pasta de destino exista
os.makedirs("../data/processed/bronze", exist_ok=True)

# Exporta cada dataframe concatenado
for table_name, df in dfs.items():
    # O arquivo será salvo na camada intermediária
    save_path = f"../data/processed/bronze/{table_name}_concat.csv"
    
    # index=False evita criar uma coluna inútil com o número da linha
    df.to_csv(save_path, index=False)
    print(f"Ingestão finalizada: {save_path} ({df.shape[0]} linhas geradas)")

print("\nIngestão completa! Os dados estão prontos para Profiling e Limpeza no Notebook 02.")

Ingestão finalizada: ../data/processed/bronze/dailyActivity_merged_concat.csv (1397 linhas geradas)
Ingestão finalizada: ../data/processed/bronze/sleepDay_merged_concat.csv (413 linhas geradas)
Ingestão finalizada: ../data/processed/bronze/weightLogInfo_merged_concat.csv (100 linhas geradas)
Ingestão finalizada: ../data/processed/bronze/hourlySteps_merged_concat.csv (46183 linhas geradas)

Ingestão completa! Os dados estão prontos para Profiling e Limpeza no Notebook 02.